FROM node:8 AS build

WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY . /app
RUN npm run build:web

FROM nginx:alpine

COPY --from=build --chown=nginx:nginx /app/dist/web /usr/share/nginx/html
COPY default.conf.template /etc/nginx/templates/default.conf.template
RUN mkdir -p /media

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
